manifest:
  self:
    west-commands: scripts/west-commands.yml

  remotes:
    - name: sdk
      url-base: https://github.com/nrfconnect
    - name: bosch
      url-base: https://github.com/boschsensortec
    - name: upstream
      url-base: https://github.com/zephyrproject-rtos

  group-filter: [-bsec2]

  projects:
    - name: sdk-nrf
      remote: sdk
      revision: v3.2.0-rc1
      path: nrf
      import:
        name-blocklist:
          - ci-tools
          - hal_altera
          - hal_cypress
          - hal_infineon
          - hal_microchip
          - hal_nxp
          - hal_openisa
          - hal_silabs
          - hal_xtensa
          - hal_ti
          - loramac-node
          - net-tools
          - edtt
          - trusted-firmware-m
          - sof
      clone-depth: 1

    - name: bsec2
      repo-path: Bosch-BSEC2-Library
      remote: bosch
      path: app/src/ext_drivers/BSEC2
      groups:
        - bsec2

    # Override Zephyr's LVGL project to track master on the same remote
    - name: lvgl
      remote: upstream
      repo-path: lvgl
      revision: c016f72d4c125098287be5e83c0f1abed4706ee5
      path: modules/lib/gui/lvgl
      
  self:
    west-commands: scripts/west-commands.yml
