// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: notification

#include "../ui.h"

void ui_Home_screen_init(void)
{
ui_Home = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Home, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Panel1 = lv_obj_create(ui_Home);
lv_obj_set_width( ui_Panel1, 200);
lv_obj_set_height( ui_Panel1, 120);
lv_obj_set_align( ui_Panel1, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0x444444), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_Panel1, LV_BORDER_SIDE_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelSource = lv_label_create(ui_Panel1);
lv_obj_set_width( ui_LabelSource, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelSource, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelSource, -35 );
lv_obj_set_y( ui_LabelSource, -40 );
lv_obj_set_align( ui_LabelSource, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelSource,"Messages");
lv_obj_clear_flag( ui_LabelSource, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_color(ui_LabelSource, lv_color_hex(0x8C8C8C), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelSource, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelTimeDelta = lv_label_create(ui_Panel1);
lv_obj_set_width( ui_LabelTimeDelta, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelTimeDelta, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelTimeDelta, 70 );
lv_obj_set_y( ui_LabelTimeDelta, -40 );
lv_obj_set_align( ui_LabelTimeDelta, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelTimeDelta,"12m");
lv_obj_clear_flag( ui_LabelTimeDelta, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_color(ui_LabelTimeDelta, lv_color_hex(0x8C8C8C), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelTimeDelta, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image1 = lv_img_create(ui_Panel1);
lv_img_set_src(ui_Image1, &ui_img_whatsapp_png);
lv_obj_set_width( ui_Image1, 16);
lv_obj_set_height( ui_Image1, 16);
lv_obj_set_x( ui_Image1, -85 );
lv_obj_set_y( ui_Image1, -40 );
lv_obj_set_align( ui_Image1, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Image1, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags

ui_LabelHeader = lv_label_create(ui_Panel1);
lv_obj_set_width( ui_LabelHeader, 180);
lv_obj_set_height( ui_LabelHeader, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelHeader, 0 );
lv_obj_set_y( ui_LabelHeader, -10 );
lv_obj_set_align( ui_LabelHeader, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelHeader,"Jakob Krantz");
lv_obj_clear_flag( ui_LabelHeader, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_color(ui_LabelHeader, lv_color_hex(0x587BF8), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelHeader, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelHeader, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TextAreaBody = lv_textarea_create(ui_Panel1);
lv_obj_set_width( ui_TextAreaBody, 180);
lv_obj_set_height( ui_TextAreaBody, 35);
lv_obj_set_x( ui_TextAreaBody, 0 );
lv_obj_set_y( ui_TextAreaBody, 25 );
lv_obj_set_align( ui_TextAreaBody, LV_ALIGN_CENTER );
lv_textarea_set_text(ui_TextAreaBody,"Blablabla");
lv_obj_clear_flag( ui_TextAreaBody, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE );    /// Flags
lv_obj_set_style_text_color(ui_TextAreaBody, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_TextAreaBody, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_TextAreaBody, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_TextAreaBody, lv_color_hex(0x444444), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_TextAreaBody, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_TextAreaBody, lv_color_hex(0x444444), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_TextAreaBody, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_TextAreaBody, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_TextAreaBody, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_TextAreaBody, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_TextAreaBody, 0, LV_PART_MAIN| LV_STATE_DEFAULT);



}
