# Copyright (c) 2025 ZSWatch Project
# SPDX-License-Identifier: Apache-2.0

"""
Image converter — converts PNG/JPG images to LVGL v9 C arrays.

The output C file can be #included into LLEXT app source code.
Supports RGB565, RGB565A8 (with alpha), and ARGB8888 color formats.
"""

import io
import logging
import struct
from enum import IntEnum
from typing import Optional

from fastapi import APIRouter, File, Form, HTTPException, UploadFile
from fastapi.responses import PlainTextResponse
from PIL import Image

logger = logging.getLogger(__name__)

router = APIRouter()


class ColorFormat(IntEnum):
    """LVGL v9 color formats."""
    RGB565 = 0x12
    RGB565A8 = 0x14
    ARGB8888 = 0x10
    L8 = 0x06


# Format metadata: bytes per pixel (for the main data, not including alpha map)
FORMAT_BPP = {
    ColorFormat.RGB565: 2,
    ColorFormat.RGB565A8: 2,   # 2 bpp + alpha map appended
    ColorFormat.ARGB8888: 4,
    ColorFormat.L8: 1,
}


def _rgb_to_565(r: int, g: int, b: int) -> int:
    """Convert 8-bit RGB to RGB565 (little-endian stored)."""
    return ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)


def _convert_image(
    img: Image.Image,
    cf: ColorFormat,
    var_name: str,
) -> str:
    """Convert a PIL Image to an LVGL v9 C array source file."""
    # Ensure RGBA
    img = img.convert("RGBA")
    w, h = img.size
    pixels = list(img.getdata())

    data_bytes = bytearray()
    alpha_bytes = bytearray()  # Used for RGB565A8

    for r, g, b, a in pixels:
        if cf == ColorFormat.RGB565:
            val = _rgb_to_565(r, g, b)
            data_bytes.extend(struct.pack("<H", val))
        elif cf == ColorFormat.RGB565A8:
            val = _rgb_to_565(r, g, b)
            data_bytes.extend(struct.pack("<H", val))
            alpha_bytes.append(a)
        elif cf == ColorFormat.ARGB8888:
            data_bytes.extend([b, g, r, a])
        elif cf == ColorFormat.L8:
            gray = int(0.299 * r + 0.587 * g + 0.114 * b)
            data_bytes.append(gray)

    # For RGB565A8, append the alpha map after the pixel data
    if cf == ColorFormat.RGB565A8:
        data_bytes.extend(alpha_bytes)

    # Calculate stride (bytes per row for the main pixel data)
    stride = w * FORMAT_BPP[cf]

    # Format name for the C code
    cf_names = {
        ColorFormat.RGB565: "RGB565",
        ColorFormat.RGB565A8: "RGB565A8",
        ColorFormat.ARGB8888: "ARGB8888",
        ColorFormat.L8: "L8",
    }
    cf_name = cf_names[cf]

    # Generate C source
    lines = []
    lines.append("/* Auto-generated by ZSWatch App Builder */")
    lines.append("/* Do not edit manually */")
    lines.append("")
    lines.append("#include <lvgl.h>")
    lines.append("")

    # Data array
    lines.append(f"#ifndef LV_ATTRIBUTE_MEM_ALIGN")
    lines.append(f"#define LV_ATTRIBUTE_MEM_ALIGN")
    lines.append(f"#endif")
    lines.append("")

    lines.append(f"static LV_ATTRIBUTE_MEM_ALIGN const uint8_t {var_name}_map[] = {{")

    # Format data as hex bytes, 16 per line
    for i in range(0, len(data_bytes), 16):
        chunk = data_bytes[i:i + 16]
        hex_vals = ", ".join(f"0x{b:02x}" for b in chunk)
        lines.append(f"    {hex_vals},")

    lines.append("};")
    lines.append("")

    # Image descriptor
    if cf == ColorFormat.RGB565A8:
        data_size = f"{w * h} * 3"  # 2 bytes pixel + 1 byte alpha
    elif cf == ColorFormat.ARGB8888:
        data_size = f"{w * h} * 4"
    elif cf == ColorFormat.RGB565:
        data_size = f"{w * h} * 2"
    elif cf == ColorFormat.L8:
        data_size = f"{w * h}"

    lines.append(f"const lv_img_dsc_t {var_name} = {{")
    lines.append(f"    .header.cf = LV_COLOR_FORMAT_{cf_name},")
    lines.append(f"    .header.magic = LV_IMAGE_HEADER_MAGIC,")
    lines.append(f"    .header.w = {w},")
    lines.append(f"    .header.h = {h},")
    lines.append(f"    .header.stride = {stride},")
    lines.append(f"    .data_size = {data_size},")
    lines.append(f"    .data = {var_name}_map,")
    lines.append("};")
    lines.append("")

    return "\n".join(lines)


@router.post("/convert-image")
async def convert_image(
    image: UploadFile = File(...),
    format: str = Form("RGB565A8"),
    var_name: Optional[str] = Form(None),
    max_width: Optional[int] = Form(None),
    max_height: Optional[int] = Form(None),
):
    """
    Convert an uploaded PNG/JPG image to an LVGL v9 C array.

    Args:
        image: The image file (PNG, JPG, BMP, GIF)
        format: Color format — "RGB565", "RGB565A8", "ARGB8888", "L8"
        var_name: C variable name (defaults to filename without extension)
        max_width: Maximum width (image is scaled proportionally)
        max_height: Maximum height (image is scaled proportionally)

    Returns:
        C source file content
    """
    # Validate format
    format_map = {
        "RGB565": ColorFormat.RGB565,
        "RGB565A8": ColorFormat.RGB565A8,
        "ARGB8888": ColorFormat.ARGB8888,
        "L8": ColorFormat.L8,
    }
    cf = format_map.get(format.upper())
    if cf is None:
        raise HTTPException(
            status_code=400,
            detail=f"Unsupported format: {format}. Use: {', '.join(format_map.keys())}"
        )

    # Read image
    try:
        data = await image.read()
        img = Image.open(io.BytesIO(data))
    except Exception as e:
        raise HTTPException(status_code=400, detail=f"Failed to read image: {e}")

    # Determine variable name
    if not var_name:
        # Use filename without extension, sanitize for C identifier
        name = image.filename or "image"
        name = name.rsplit(".", 1)[0]
        name = name.replace("-", "_").replace(" ", "_")
        # Ensure valid C identifier
        name = "".join(c if c.isalnum() or c == "_" else "_" for c in name)
        if name[0].isdigit():
            name = "img_" + name
        var_name = name

    # Resize if needed
    if max_width or max_height:
        orig_w, orig_h = img.size
        new_w, new_h = orig_w, orig_h

        if max_width and orig_w > max_width:
            scale = max_width / orig_w
            new_w = max_width
            new_h = int(orig_h * scale)

        if max_height and new_h > max_height:
            scale = max_height / new_h
            new_h = max_height
            new_w = int(new_w * scale)

        if (new_w, new_h) != (orig_w, orig_h):
            img = img.resize((new_w, new_h), Image.Resampling.LANCZOS)
            logger.info(f"Resized {orig_w}x{orig_h} → {new_w}x{new_h}")

    # Warn if image is very large
    w, h = img.size
    if w * h > 240 * 240:
        logger.warning(f"Image is large ({w}x{h}), consider resizing for 240x240 display")

    # Convert
    c_source = _convert_image(img, cf, var_name)

    output_filename = f"{var_name}.c"
    logger.info(f"Converted {image.filename} → {output_filename} ({w}x{h}, {format})")

    return PlainTextResponse(
        content=c_source,
        headers={
            "Content-Disposition": f'attachment; filename="{output_filename}"',
            "X-Image-Width": str(w),
            "X-Image-Height": str(h),
            "X-Color-Format": format,
        },
    )
