on:
    pull_request:
    workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml

  # Temporary disable until we have a fixed HW test setup
  #test:
  #  needs: [build]
  #  uses: ./.github/workflows/test.yml
